export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    VERIFY_EMAIL: '/auth/verify-email',
  },
  USERS: {
    PROFILE: '/users/profile',
    UPDATE: '/users/profile',
    UPLOAD_AVATAR: '/users/avatar',
    SEARCH: '/users/search',
    GET_BY_ID: (id: string) => `/users/${id}`,
  },
  ARTWORKS: {
    LIST: '/artworks',
    CREATE: '/artworks',
    GET_BY_ID: (id: string) => `/artworks/${id}`,
    UPDATE: (id: string) => `/artworks/${id}`,
    DELETE: (id: string) => `/artworks/${id}`,
    UPLOAD_IMAGE: '/artworks/upload',
    SEARCH: '/artworks/search',
  },
  COMMISSIONS: {
    LIST: '/commissions',
    CREATE: '/commissions',
    GET_BY_ID: (id: string) => `/commissions/${id}`,
    UPDATE: (id: string) => `/commissions/${id}`,
    UPDATE_STATUS: (id: string) => `/commissions/${id}/status`,
    ADD_MILESTONE: (id: string) => `/commissions/${id}/milestones`,
    UPDATE_MILESTONE: (id: string, milestoneId: string) => `/commissions/${id}/milestones/${milestoneId}`,
  },
  PAYMENTS: {
    CREATE: '/payments',
    GET_BY_ID: (id: string) => `/payments/${id}`,
    PROCESS: (id: string) => `/payments/${id}/process`,
    REFUND: (id: string) => `/payments/${id}/refund`,
    HISTORY: '/payments/history',
    ESCROW_RELEASE: (id: string) => `/payments/${id}/release`,
  },
  MESSAGES: {
    CONVERSATIONS: '/messages/conversations',
    CREATE_CONVERSATION: '/messages/conversations',
    GET_MESSAGES: (conversationId: string) => `/messages/conversations/${conversationId}`,
    SEND_MESSAGE: '/messages',
    MARK_READ: (messageId: string) => `/messages/${messageId}/read`,
    UPLOAD_ATTACHMENT: '/messages/upload',
  },
  EVENTS: {
    LIST: '/events',
    CREATE: '/events',
    GET_BY_ID: (id: string) => `/events/${id}`,
    UPDATE: (id: string) => `/events/${id}`,
    DELETE: (id: string) => `/events/${id}`,
    ATTEND: (id: string) => `/events/${id}/attend`,
    SEARCH: '/events/search',
  },
  UPLOAD: {
    IMAGE: '/upload/image',
    FILE: '/upload/file',
    AVATAR: '/upload/avatar',
  },
} as const;
